---
email_cluster: server@domeniulmeunou.ro
ansible_local_ip: 192.168.1.100
admin_local_ip: 192.168.1.134
download_path: /root/download_cluster
primary_domain: domeniulmeunou.ro
primary_domain_user: domeniulmeunou
primary_domain_password: domeniulmeunou
primary_domain_uid: 3030
primary_domain_gid: 3030
storage_path: /storage/websites
nfs_ip_mount: 192.168.1.101

# haproxy
# compile haproxy with lua |  1 = enable / 0 = disable
compile_haproxy_with_lua: 0

# fpm
install_php73: 1
install_php74: 1
# php73 / php74
default_php_version: php73
# 0 - ondemand / 1 - dynamic / 2 - static
php_fpm_pm_type: 0

# mariadb global variables
mariadb_version: 10.4
# Define interface in which to bind
# ex. eth0|eth1|enp0s3|enp0s8|ens33
galera_cluster_bind_interface: 'ens33'
# 0 - mariabackup / 1 - rsync
galera_cluster_sst_method: 0
galera_cluster_root_password: TfyhHtqDD3dd6hh2MRvxyxx
galera_cluster_mariadbbackup_password: kDyS7Ve93nTHmCg2xyxx

#rsyslog
### first server from lb group to receive logs
rsyslog_remote: 192.168.1.98

# Set the mode for new directories
rsyslog_dircreatemode: "0700"

# Set the mode for new files
rsyslog_filecreatemode: "0644"