---
- name: Copy Haproxy config file
  template:
    src: haproxy-cluster-mode-2.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Enable haproxy service
  systemd:
    name: haproxy
    state: started
    enabled: yes
    daemon_reload: yes