---
- name: Copy nginx config files - cluster_setup_mode 10 - Step 2 | nginx
  template:
    src: 'nginx_primary_domain.conf.j2'
    dest: "/etc/nginx/conf.d/{{ primary_domain }}.conf"
    owner: root
    group: root
    mode: '0600'
  when: cluster_setup_mode == 10 

- name: Copy nginx config files - cluster_setup_mode 2 or 3 - Step 2 | nginx
  template:
    src: 'nginx_primary_domain.conf.j2'
    dest: "/etc/nginx/conf.d/{{ primary_domain }}.conf"
    owner: root
    group: root
    mode: '0600'
  when: ( cluster_setup_mode == 2 ) or ( cluster_setup_mode == 3 )