---
- name: Determine if domain {{ primary_domain }} exist in httpd.
  stat:
    path: "/etc/httpd/conf.d/{{ primary_domain }}.conf"
  register: primary_domain_nginx_result

- name: Fail if domain {{ primary_domain }} exist in httpd. 
  fail:
    msg: "Domain {{ primary_domain }} exists on this server."
  when: primary_domain_nginx_result.stat.exists == True