---
- name: reloaded httpd service
  systemd:
    name: httpd
    state: reloaded
  when: ( cluster_setup_mode == 1 ) and ( inventory_hostname in groups['nodes'] )

- name: reloaded nginx service | nginx
  systemd:
    name: nginx
    state: reloaded
  when: ( cluster_setup_mode in [2, 3] ) and ( inventory_hostname in groups['nodes'] )

- name: restarted haproxy service
  systemd:
    name: haproxy
    state: restarted
  when: ( cluster_setup_mode in [1, 2] ) and ( inventory_hostname in groups['lb'] )