---
- name: Install fail2ban packages | fail2ban
  yum:
    name: "{{ fail2ban_packages }}"
    state: present
  retries: 3

- name: Copy fail.local | fail2ban
  template:
    src: jail.local.j2
    dest: "/etc/fail2ban/jail.local"
    owner: root
    group: root
    mode: '0644'

- name: Enable fail2ban | fail2ban
  systemd:
    name: "fail2ban"
    state: restarted
    enabled: yes