---
- name: Check 443 port numbers are accessible from current host - Single Server | haproxy
  wait_for:
    host: "127.0.0.1"
    port: 443
    state: started         # Port should be open
    delay: 0               # No wait before first check (sec)
    timeout: 3             # Stop checking after timeout (sec)
  ignore_errors: yes

- name: Check 80 port numbers are accessible from current host - Single Server | haproxy
  wait_for:
    host: "127.0.0.1"
    port: 80
    state: started         # Port should be open
    delay: 0               # No wait before first check (sec)
    timeout: 3             # Stop checking after timeout (sec)
  ignore_errors: yes