---
- import_tasks: haproxy-prepare.yml

- import_tasks: haproxy-ssl.yml

- import_tasks: haproxy-cluster-mode-1.yml
  when: >
    cluster_setup_mode == 1

- import_tasks: haproxy-cluster-mode-2.yml
  when: >
    cluster_setup_mode == 2

- import_tasks: haproxy-cluster-mode-10.yml
  when: >
    cluster_setup_mode == 10

- import_tasks: haproxy-check-cluster.yml
  when: cluster_setup_mode != 10

- import_tasks: haproxy-check-single.yml
  when: cluster_setup_mode == 10