---
# tasks file for ansible-logrotate
- name: Copy logrotate.d files
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  become: true
  with_items:
    - 'etc/logrotate.d/cron'
    - 'etc/logrotate.d/dmesg'
    - 'etc/logrotate.d/mysqld'
    - 'etc/logrotate.d/secure'