---
  - set_fact:
      path_to_remove_1: "/storage/websites/{{ primary_domain_user }} "
      path_to_remove_2: "/home/{{ primary_domain_user }}/"

  - name: Remove storage directory for user {{ primary_domain_user }}
    file:
      path: "/storage/websites/{{ primary_domain_user }}"
      state: absent

  - name: Remove symlink /home/{{ primary_domain_user }}
    file:
      path: "/home/{{ primary_domain_user }}"
      state: absent

  - name: remove path for {{ primary_domain_user }} from /etc/exports
    lineinfile:
      path: /etc/exports
      state: absent
      regexp: ".*{{ path_to_remove_1 | regex_escape() }}"

  - name: remove path for {{ primary_domain_user }} from /etc/init.d/storage_mount
    lineinfile:
      path: /etc/init.d/storage_mount
      state: absent
      regexp: ".*{{ path_to_remove_2 | regex_escape() }}.*"

  - name: reload nfs
    shell: "exportfs -ra"

  - name: Remove certs if exist
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/etc/haproxy/ssl/{{ primary_domain }}.keycacrt.crt"