---
- import_tasks: cluster.yml
  when: ( cluster_setup_mode == 1 ) or ( cluster_setup_mode == 2 ) or ( cluster_setup_mode == 3 )

- import_tasks: single.yml
  when: >
    cluster_setup_mode == 10

- import_tasks: domain-ssh.yml
  when: primary_domain_ssh_key == 1 and groups['lb']