---
- name: alert if variable does not exist
  fail:
    msg: "{{ item }} is not defined"
  when: "{{ item }} is not defined"
  with_items:
    - username
    - database

- name: Create a new database with name {{ database }}
  mysql_db:
    name: "{{ database }}"
    state: absent
    login_password: "{{ galera_cluster_root_password }}"

- name: Create a new username {{ username }} and grant access to {{ database }}
  mysql_user:
    name: "{{ username }}"
    state: absent
    login_password: "{{ galera_cluster_root_password }}"
    host: "%"