---
- name: Get running processes nginx list | nginx
  ignore_errors: yes
  shell: "ps -few | grep nginx | awk '{print $2}'"
  register: running_processes

- name: Kill running processes | nginx
  ignore_errors: yes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: yes
  register: nginx_processes

- name: Force kill stuck processes | nginx
  ignore_errors: yes
  shell: "kill -9 {{ item }}"
  with_items: "{{ nginx_processes.results | select('failed') | map(attribute='item') | list }}"

- name: Nginx prepare | ensure a list of packages installed | nginx
  yum:
    name:
      - pcre
      - pcre-devel
      - zlib
      - wget
      - libxml2
      - libxml2-devel
      - libxslt-devel
      - libxslt
      - gcc
      - wget
      - make
      - libaio-devel
      - pcre-devel
      - openssl-devel
      - expat-devel
      - zlib-devel
      - libxslt-devel
      - gd-devel
      - GeoIP-devel
      - gperftools-devel
      - perl-ExtUtils-Embed
      - git
      - readline-devel
      - python-cryptography
    state: present

- name: Add group nginx
  group:
    name: nginx
    state: present

- name: Add user nginx
  user:
    name: nginx
    shell: "/sbin/nologin"
    home: "/var/cache/nginx"
    group: nginx
    system: yes
    state: present

- name: Create /var/lib/nginx/tmp/client_body | nginx
  file:
    path: "/var/lib/nginx/tmp/client_body"
    state: directory
    owner: nginx
    group: root
    mode: '0755'

- name: Create /var/www/nginx/ folder | nginx
  file:
    path: "/var/www/nginx"
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'

- name: Create /etc/nginx/conf.d/  | nginx
  file:
    path: "/etc/nginx/conf.d/"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Delete /usr/share/nginx/html folder | nginx
  file:
    path: "/usr/share/nginx/html"
    state: absent

- name: Analyzing the directories to delete... | nginx
  find:
    paths: "{{ download_path }}"
    patterns: "nginx-*"
    use_regex: true
    file_type: directory
  register: folders_to_delete

- name: Deleting the directories...
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ folders_to_delete.files }}"

- name: Analyzing the files to delete... | nginx
  find:
    paths: "{{ download_path }}"
    patterns: "nginx-*"
    use_regex: true
    file_type: file
  register: files_to_delete

- name: Deleting the directories...
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: Generate .htpasswd password for user {{ phpmyadmin_auth_user }} | nginx
  shell: openssl passwd -apr1 -in <(printf "{{ phpmyadmin_auth_password }}")
  args:
    executable: /bin/bash
    chdir: "{{ download_path }}"
  register: command_output_passwd_auth_phpmyadmin

- set_fact:
    passwd_auth_phpmyadmin: "{{ command_output_passwd_auth_phpmyadmin.stdout }}"

- name: Download nginx-{{ nginx_lb_version }} | nginx
  get_url:
    url: "https://nginx.org/download/nginx-{{ nginx_lb_version }}.tar.gz"
    dest: "{{ download_path }}"

- name: Unpacking nginx-{{ nginx_lb_version }} | nginx
  unarchive:
    copy: no
    dest: "{{ download_path }}"
    src: "{{ download_path }}/nginx-{{ nginx_lb_version }}.tar.gz"
  register: nginx_lb_version_source_unpack