---
- name: Delete folder phpmyadmin if exist | phpmyadmin
  file:
    path: "/var/www/nginx/phpmyadmin"
    state: absent

- name: Download & Unarchive Phpmyadmin | phpmyadmin
  unarchive:
    src: "https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/phpMyAdmin-{{ phpmyadmin_version }}-english.tar.gz"
    dest: "/var/www/nginx/"
    remote_src: yes
    group: nginx
    owner: nginx
    extra_opts:
      - --transform
      - s/^phpMyAdmin-{{ phpmyadmin_version }}-english/phpmyadmin/
  when: cluster_setup_mode == 2 or cluster_setup_mode == 3

- name: Delete folder phpmyadmin if exist | phpmyadmin
  file:
    path: "/var/www/nginx/phpMyAdmin-{{ phpmyadmin_version }}-english"
    state: absent
  when: cluster_setup_mode == 2 or cluster_setup_mode == 3

- name: Delete folder phpmyadmin if exist | phpmyadmin
  file:
    path: "/var/www/html/phpMyAdmin-{{ phpmyadmin_version }}-english"
    state: absent
  when: cluster_setup_mode == 1