---
- name: Install EPEL Repo - Amazon | epel
  yum:
   name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
   state: present

- name: yum-config-manager --enable epel - Amazon | epel
  command: yum-config-manager --enable epel
  args:
    warn: no

