---
- name: Create folder - martiadb_max_open_files
  file:
    path: /etc/systemd/system/mariadb.service.d
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Add the overriding file - martiadb_max_open_files
  template:
    src: "etc/systemd/system/mariadb.service.d/max-open-files.conf.j2"
    dest: "/etc/systemd/system/mariadb.service.d/max-open-files.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Just force systemd to reread configs - martiadb_max_open_files
  systemd:
    daemon_reload: yes