- hosts: all
  user: root
  become: true
  gather_facts: yes
  vars_files:
    - vars/new-domain-vars.yml
    - vars/setup-cluster-vars.yml
  roles:
          - { role: ansible-new-domain-cluster, tags: new-domain-cluster }