- hosts: all
  user: root
  become: false
  gather_facts: yes
  vars_files:
  - vars/global-vars.yml
  - vars/setup-cluster-vars.yml
  roles:
          - { role: ansible-cluster-prepare, tags: cluster-prepare }
          - { role: repo-epel, tags: repo-epel }
          - { role: ansible-change-hostname, tags: change-hostname }
          - { role: ansible-disable-selinux, tags: disable-selinux }
          - { role: ansible-iptables-services, tags: iptables }
          - { role: ansible-useradd, tags: useradd }
          - { role: ansible-logrotate, tags: logrotate }
          - { role: ansible-ntp-client, tags: ntp-client }
          - { role: ansible-fail2ban, tags: fail2ban }
#          - { role: ansible-rsyslog, tags: rsyslog }
  any_errors_fatal: true

- hosts: lb
  user: root
  become: false
  gather_facts: no
  vars_files:
  - vars/global-vars.yml
  - vars/setup-cluster-vars.yml
  roles:
          - { role: ansible-haproxy, when: cluster_setup_mode == 1 or cluster_setup_mode == 2, tags: haproxy }
          - { role: ansible-nginx-lb, when: cluster_setup_mode == 3, tags: nginx-lb }
          - { role: ansible-acme.sh, tags: acme.sh }

- hosts: nfs
  user: root
  become: false
  gather_facts: no
  vars_files:
  - vars/global-vars.yml
  - vars/setup-cluster-vars.yml
  roles:
    - { role: ansible-storage, tags: nfs-server }

- hosts: nodes
  user: root
  become: false
  strategy: free
  gather_facts: no
  serial: 3
  vars_files:
  - vars/global-vars.yml
  - vars/setup-cluster-vars.yml
  roles:
    - { role: repo-remi, tags: repo-remi }
    - { role: ansible-storage-client, tags: storage-client }
    - { role: ansible-nginx, when: cluster_setup_mode == 2 or cluster_setup_mode == 3, tags: nginx }
    - { role: ansible-httpd, when: cluster_setup_mode == 1, tags: httpd }
    - { role: ansible-php-fpm, tags: php-fpm }
    # - { role: ansible-lighttpd, when: cluster_setup_mode == 1, tags: lighttpd }
    - { role: ansible-composer-tool, tags: composer-tool }
    - { role: ansible-phpmyadmin, tags: phpmyadmin }

- hosts: galera_cluster_nodes
  user: root
  become: false
  gather_facts: no
  vars_files:
  - vars/global-vars.yml
  - vars/setup-cluster-vars.yml
  roles:
    - { role: ansible-mariadb-galera-cluster, tags: mariadb-galera-cluster }


- hosts: all
  user: root
  become: false
  gather_facts: no
  vars_files:
  - vars/global-vars.yml
  - vars/setup-cluster-vars.yml
  roles:
    - { role: ansible-final-check, tags: final-check }