---
  - name: Install libselinux as prerequisite for SELinux Ansible module
    yum:
      name: "{{ libselinux_packages }}"
      state: present

  - name: Disable SELinux at next reboot
    selinux:
      state: disabled

  - name: Set SELinux in permissive mode until the machine is rebooted
    command: /usr/sbin/setenforce 0
    ignore_errors: true
    changed_when: false